name: Docker Build, Scout and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construction de l'image Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-main:latest .

      - name: Analyse avec Docker Scout
        run: docker scout cves ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-main:latest

      - name: Pousser l'image vers Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-main:latest
